Use armv8a Apple local labels with clang.
Details:
- Modified the cpp guard protecting the Apple local label macros in
  kernels/armv8a/3/armv8a_asm_utils.h so that the macros are processed
  not only when __APPLE__ is #defined but also when __clang__ is
  #defined.
- @egaudry and I both saw this issue on Linux with Clang 10.
- The error that prompted this tweak manifested as:
    ```
    Compiling obj/thunderx2/kernels/armv8a/3/sup/bli_gemmsup_rv_armv8a_asm_d4x8m.o ('t
hunderx2' CFLAGS for kernels)
    kernels/armv8a/3/bli_gemm_armv8a_asm_d6x8.c:171:49: fatal error: invalid symbol re
definition
            "                                            \n\t"
                                                           ^
    <inline asm>:90:5: note: instantiated into assembly here
               .SLOOPKITER:
               ^
    1 error generated.
    ```
- (cherry picked from commit 0ab20c0e72402ba0b17fe2c3ed3e16bf2ace0fd3)